version: "3"
services:
  app:
    image: ryrahul7/gpt-clone-app:latest
    container_name: nextjs-app
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
